---
- hosts: all
  user: ubuntu
  become: True
#  user: root
  roles:
    - preconf
  tags: preconf

- hosts: bootnode
  become: True
  vars:
    nginx_headers: "on"
    PROXY_PORT: "8545"
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
  roles:
    - bootnode
  tags:
    - bootnode

- hosts: validator
  become: True
  vars:
    username: "validator"
    users:
      - name: "validator"
    home: "/home/validator"
  roles:
    - validator
  tags:
    - validator

- hosts: netstat
  become: True
  vars:
    nginx_headers: "off"
    PROXY_PORT: "3000"
    NETSTATS_SERVER: "http://localhost:3000"
    username: "netstat"
    users:
      - name: "netstat"
    home: "/home/netstat"
  roles:
    - netstat
  tags:
    - netstat

- hosts: explorer
  become: True
  vars:
    nginx_headers: "off"
    PROXY_PORT: "3000"
    explorerS_SERVER: "localhost"
    username: "explorer"
    users:
      - name: "explorer"
    home: "/home/explorer"
  roles:
    - explorer
  tags:
    - explorer

- hosts: moc
  become: True
  vars:
    username: "moc"
    users:
      - name: "moc"
    home: "/home/moc"
  roles:
    - moc
  tags:
    - moc
