---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: add nodejs repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ node_key_id }}"
    state: present

- name: Add nodejs repository
  apt_repository:
    repo: 'deb {{ node_source_deb }} {{ansible_distribution_release}} main'
    state: present

- name: Install nodejs packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - nodejs
